### ISSUE TITLE
HTTP code 502 

### ISSUE THREAD

**Issue by onioner** [intel/asynch_mode_nginx#14]
Hi Team.

When I configured "proxy_ssl_asynch on", why nginx return 502?  But there is no errors if I configure "ssl_asynch  on".

load_module modules/ngx_ssl_engine_qat_module.so;
ssl_engine {
    use_engine qat;
    default_algorithms RSA,EC,DH,PKEY_CRYPTO;
    qat_engine {
        qat_offload_mode async;
        qat_notify_mode poll;
    }
}

server {
            listen          443 ssl;
            location /ssl {
                proxy_pass http://unix:/usr/local/nginx/nginx.sock;
                proxy_ssl_asynch on;
            }
 }

And there is error.log:
[error] 31995#0: *19 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream

OS: CentOS 6.8
kernel: 2.6.32-642.el6.x86_64
asynch_mode_nginx version: 0.3.6
openssl version:  1.1.0g
QAT Driver version: qat1.7.l.4.4.0-00023
QAT_Engine version: 0.5.39

Thanks in advance !

**Comment by daweiq** [comment]
Hi, 

For "ssl_async on" configuration, do you mean configure Nginx as a web server instead of a proxy?
The config looks like the following: 
```
server {
       listen 443 ssl;
       ssl_asynch on;

       location /ssl {
           ....
       }
}
```
The "ssl_async on" does not work with proxy_pass directive, you have to use "proxy_ssl_asynch on" command for upstream server async acceleration. 
So, if you configure Nginx as a web server, it only reply client with local file, has nothing to do with upstream server. 

The "wrong version number" error you show, seems to be a version restriction for TLS/SSL in upstream server. So, if the Nginx proxy server select TLS1.2 for handshake, while upstream server not accept it, the error happened. 

Does this make sense?


Best regards,
David Qian

**Comment by onioner** [comment]
Hi, @daweiq 
Thank for your reply, I use async_nginx as a proxy server, and its config like this
```
server {
       listen 443 ssl;
       proxy_ssl_asynch on;
       ssl_protocols   TLSv1 TLSv1.1 TLSv1.2;

       location /ssl {
           proxy_pass http://xx.xx.xx.xx:80;
       }
}
```
I proxy port 443 to port 80 of the upstream server,  so it may not be the reason you said about TLS.  Is there any other reason?

Thanks in advance !

**Comment by weicz11** [comment]
> Hi, @daweiq
> Thank for your reply, I use async_nginx as a proxy server, and its config like this
> 
> ```
> server {
>        listen 443 ssl;
>        proxy_ssl_asynch on;
>        ssl_protocols   TLSv1 TLSv1.1 TLSv1.2;
> 
>        location /ssl {
>            proxy_pass http://xx.xx.xx.xx:80;
>        }
> }
> ```
> The async_nginx always return 502. But If I configure `ssl_asynch on` instead of `proxy_ssl_asynch on`, there isn't any errors, and aysnc_nginx can return the correct content.
> I proxy port 443 to port 80 of the upstream server, so it may not be the reason you said about TLS. Is there any other reasons?
> 
> Thanks in advance !

"proxy_pass http://xx.xx.xx.xx:80;“ means you setup a http server instead of a https server as the backend service. So you can't not connect it via SSL connection, you should also *NOT* config it using "proxy_ssl_asynch on;" because it will connection it using a SSL connection.
If you confirm the backend service is *NOT* a https server, you should use the below  config
`server {
       listen 443 ssl;
       ssl_asynch on;
       ssl_protocols   TLSv1 TLSv1.1 TLSv1.2;

       location /ssl {
           proxy_pass http://xx.xx.xx.xx:80;
       }
}`
which means nginx accept client connection via 443 port as a SSL connection which is in async ssl mode.

If you want to upstream to a SSL backend server, you should use 
`server {
       listen 443 ssl;
       ssl_asynch on;
       ssl_protocols   TLSv1 TLSv1.1 TLSv1.2;

       location /ssl {
           proxy_pass http**s**://xx.xx.xx.xx:80;
           proxy_ssl_asynch on;
       }
}`
And you must make sure the backend server is a *HTTPS* server. The port "80" looks strange as a SSL port.

**Comment by onioner** [comment]
Thanks @weicz11  very much !  It seems that I didn't understand `ssl_asynch` and `proxy_ssl_asynch` correctly.
