### ISSUE TITLE
ssl_engine directive conflicts with nginix 1.16 directive of the same name

### ISSUE THREAD

**Issue by jmechalas** [intel/asynch_mode_nginx#29]
nginx 1.16 [added a directive with the name "ssl_engine"](http://nginx.org/en/docs/ngx_core_module.html#ssl_engine) in the event module to access OpenSSL engines. It has a different syntax than the one in this module, but generally speaking the name conflict is an issue.

**Comment by zhangp8x** [comment]
Dear @jmechalas 
The key "ssl_engine" existed since nginx-0.1.45-RELEASE, here:
http://hg.nginx.org/nginx/annotate/b09ee85d0ac8/src/event/ngx_event_openssl.c#l22

Async-nginx need to use this keyword to enable our QAT-Engine, so we remove these codes. You can check the sample configuration file here:
https://github.com/intel/asynch_mode_nginx/blob/master/conf/nginx.QAT-sample.conf

**Comment by jmechalas** [comment]
Removing the _vendor's_ keyword just because you want to use a keyword with the same name is not a great solution. In fact, I can't think of a worse solution as it breaks the vendor's original functionality.

Why not choose a new/unique keyword?

**Comment by zhangp8x** [comment]
@jmechalas:
In our async Nginx, the original simple ssl_engine directive is deleted and replaced with ssl_engine framework.
This change involves the adding of a new core module and does not depend on the loading of qat module.
In other words, no matter whether to load the qat module, we can only use the new ssl_engine framework.

**Comment by daweiq** [comment]
Close it since now more update.
