### ISSUE TITLE
SSL_do_handshake() failed

### ISSUE THREAD

**Issue by htang555** [intel/asynch_mode_nginx#33]
Hello,

I am getting an SSL handshake failure when running a request through the default supplied nginx.QAT-sample.conf (for testing).

Environment:

Centos 7.7.1908
QAT_Engine v0.5.43
QATzip v1.0.1
Openssl 1.1.1c
Intel Communications Chipset 8950 Series

Am getting this error specifically:

 *3 SSL_do_handshake() failed (SSL: error:800650ED:lib(128):build_decrypt_op_buf:p q dmp dmq convert to fb failure error:141EC044:SSL routines:tls_construct_server_key_exchange:internal error) while SSL handshaking

Let me know if you need anymore information.

**Comment by zhangp8x** [comment]
@htang555 :

When user didn’t have root authority, this issue may happened,
and the following debug log can be found:
“hugepage_alloc_slab:211 mmap on huge page memory allocation failed”
The huge page memory allocation failed because user didn't have root authority.

Solution:
(1)	Add “user root;” in Nginx configuration file.
OR
(2)	Modify execution permission of following files.
/dev/qat_*
/dev/usdm_drv
/dev/uio*
/dev/hugepages
/usr/local/lib/libqat_s.so
/usr/local/lib/libusdm_drv_s.so

BRs/Thx

**Comment by htang555** [comment]
@zhangp8x 

Thanks for the quick reply. You were right it was a permissions issue.
